# 1. Операции с данными

## 1.1 Очистка пустых значений

Сначала мы создадим объект типа Series содержащий ошибки и пропуски в данных

In [2]:
import pandas as pd
import numpy as np

In [14]:
trash = pd.Series(['1', '2', None, '4', np.nan])
trash

0       1
1       2
2    None
3       4
4     NaN
dtype: object

In [15]:
trash.isnull()

0    False
1    False
2     True
3    False
4     True
dtype: bool

Для удаления пропущенных значений чаще всего используют команду dropna() из состава Pandas

In [12]:
trash.dropna()

0    1
1    2
3    4
dtype: object

Давайте теперь посмотрим как это работает с DataFrame

In [35]:
df = pd.read_csv('marketing_eng.csv')
df.shape

(15223, 13)

In [32]:
df.dropna()

,TARGET,AGE,SOCSTATUS_WORK_FL,SOCSTATUS_PENS_FL,GENDER,EDUCATION,MARITAL_STATUS,ORG_TP_STATE,JOB_DIR,PERSONAL_INCOME,OWN_AUTO,WORK_TIME,LOAN_MAX_DLQ_AMT
0,0,49,1,0,1,Среднее специальное,Состою в браке,Частная компания,Вспомогательный техперсонал,5000.0,0,18.0,1580.00
1,0,32,1,0,1,Среднее,Состою в браке,Индивидуальный предприниматель,Участие в основ. деятельности,12000.0,0,97.0,4020.00
2,0,52,1,0,1,Неполное среднее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,9000.0,0,84.0,0.00
3,0,39,1,0,1,Высшее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,25000.0,0,168.0,1590.00
4,0,30,1,0,0,Среднее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,12000.0,0,101.0,2230.00
5,0,29,1,0,0,Среднее,Гражданский брак,Частная компания,Адм-хоз. и трансп. службы,12000.0,1,40.0,0.00
6,0,35,1,0,0,Высшее,Разведен(а),Государственная комп./учреж.,Участие в основ. деятельности,15000.0,0,6.0,0.00
7,0,41,1,0,1,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,6000.0,0,6.0,0.00
8,0,53,1,0,0,Высшее,Состою в браке,Частная компания,Участие в основ. деятельности,100000.0,0,156.0,0.00
9,0,43,1,0,1,Среднее специальное,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,7000.0,0,72.0,0.00
10,0,54,1,0,1,Среднее специальное,Не состоял в браке,Государственная комп./учреж.,Пр-техн. обесп. и телеком.,19000.0,0,120.0,0.00
11,1,26,1,0,0,Среднее специальное,Не состоял в браке,Государственная комп./учреж.,Участие в основ. деятельности,18000.0,0,27.0,0.00
12,1,62,0,1,0,Среднее,Гражданский брак,Частная компания,Участие в основ. деятельности,7000.0,1,48.0,0.00
13,0,45,1,0,1,Среднее специальное,Разведен(а),Государственная комп./учреж.,Служба безопасности,12000.0,0,72.0,810.00
14,0,38,1,0,1,Высшее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,20000.0,0,120.0,0.00
15,1,41,1,0,1,Высшее,Разведен(а),Индивидуальный предприниматель,Участие в основ. деятельности,60000.0,0,168.0,0.00
17,0,29,1,0,1,Среднее специальное,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,5200.0,0,8.0,0.00
18,1,34,1,0,0,Среднее,Гражданский брак,Частная компания,Участие в основ. деятельности,35000.0,0,13.0,1439.94
19,0,28,1,0,1,Высшее,Не состоял в браке,Частная компания,Участие в основ. деятельности,15000.0,0,60.0,0.00
20,0,37,1,0,1,Высшее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,10000.0,0,192.0,0.00
21,0,42,1,0,1,Среднее специальное,Состою в браке,Частная компания,Участие в основ. деятельности,10000.0,0,76.0,0.00
22,0,45,1,0,1,Высшее,Разведен(а),Государственная комп./учреж.,Участие в основ. деятельности,14000.0,0,120.0,0.00
23,0,32,1,0,1,Среднее специальное,Не состоял в браке,Государственная комп./учреж.,Участие в основ. деятельности,10000.0,1,108.0,0.00
24,0,33,1,0,1,Среднее специальное,Состою в браке,Индивидуальный предприниматель,Участие в основ. деятельности,8000.0,0,24.0,0.00
25,0,38,1,0,1,Среднее специальное,Не состоял в браке,Индивидуальный предприниматель,Участие в основ. деятельности,13000.0,0,18.0,2742.25
26,0,27,1,0,1,Высшее,Состою в браке,Частная компания,Участие в основ. деятельности,12500.0,1,60.0,1411.31
27,1,31,1,0,1,Среднее специальное,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,12000.0,0,15.0,5760.00
28,0,40,1,0,0,Среднее специальное,Состою в браке,Частная компания,Участие в основ. деятельности,20000.0,0,2.0,0.00
30,0,40,1,0,1,Среднее специальное,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,11000.0,1,96.0,0.00
31,0,27,1,0,0,Высшее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,15000.0,0,108.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15189,0,23,1,0,1,Среднее специальное,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,10000.0,0,30.0,0.00
15190,0,25,1,0,1,Среднее,Не состоял в браке,Частная компания,Участие в основ. деятельности,10000.0,0,6.0,0.00
15192,0,42,1,0,1,Среднее специальное,Состою в браке,Частная компания,Участие в основ. деятельности,8000.0,0,60.0,0.00
15193,0,36,1,0,1,Высшее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,12000.0,0,204.0,0.00
15194,0,49,1,0,1,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,10000.0,0,36.0,0.00
15195,0,51,1,1,1,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,10000.0,0,360.0,0.00
15198,0,49,1,0,1,Среднее специальное,Состою в браке,Индивидуальный предприниматель,Участие в основ. деятельности,7000.0,0,72.0,0.00
15199,0,28,1,0,0,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,10000.0,0,18.0,0.00
15200,1,34,1,0,0,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,8000.0,0,36.0,605.59
15201,0,56,1,1,1,Высшее,Состою в браке,Частная компания,Участие в основ. деятельности,25000.0,0,84.0,0.00
15202,0,34,1,0,1,Среднее специальное,Состою в браке,Частная компания,Снабжение и сбыт,10000.0,0,7.0,0.00
15203,0,40,1,0,1,Среднее специальное,Состою в браке,Частная компания,Снабжение и сбыт,12000.0,0,8.0,0.00
15204,1,43,1,0,0,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,7000.0,0,27.0,0.00
15205,0,33,1,0,1,Высшее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,12000.0,0,160.0,0.00
15206,0,56,1,0,1,Среднее,Вдовец/Вдова,Частная компания,Участие в основ. деятельности,14500.0,0,384.0,0.00
15207,0,25,1,0,1,Среднее,Не состоял в браке,Индивидуальный предприниматель,Участие в основ. деятельности,12000.0,0,24.0,0.00
15208,0,37,1,0,1,Среднее специальное,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,8000.0,0,60.0,0.00
15209,1,48,1,0,1,Среднее специальное,Не состоял в браке,Частная компания,Участие в основ. деятельности,7000.0,0,6.0,0.00
15210,0,30,1,0,1,Среднее специальное,Состою в браке,Индивидуальный предприниматель,Участие в основ. деятельности,10000.0,0,12.0,0.00
15211,0,35,1,0,1,Высшее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,10000.0,0,48.0,0.00
15212,0,55,1,0,0,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,10000.0,1,204.0,0.00
15213,1,36,1,0,0,Среднее,Состою в браке,Частная компания,Вспомогательный техперсонал,15000.0,0,48.0,0.00
15214,0,31,1,0,1,Высшее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,8100.0,0,96.0,0.00
15215,0,35,1,0,1,Среднее специальное,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,9500.0,1,120.0,0.00
15216,0,61,1,0,0,Среднее,Не состоял в браке,Частная компания,Участие в основ. деятельности,13000.0,1,132.0,3300.00
15217,0,39,1,0,1,Среднее специальное,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,10000.0,0,108.0,0.00
15218,0,25,1,0,0,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,12000.0,0,48.0,0.00
15219,0,51,1,0,1,Среднее специальное,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,10000.0,0,156.0,0.00
15220,0,22,1,0,1,Среднее,Не состоял в браке,Индивидуальный предприниматель,Кадровая служба и секретариат,6000.0,0,48.0,0.00
15222,0,37,1,0,0,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,20000.0,0,36.0,0.00

Следует помнить, что выполнение операции не приведет к его изменению если вы его не перезапишите в память

In [33]:
df.shape

(15223, 13)

In [34]:
df = df.dropna()
df.shape

(13855, 13)

Можно удалять как колонки так и строки. По умолчанию - удаляются строки. Задав параметр axis - можно удаляить колонку

In [37]:
df.dropna(axis='columns')

,TARGET,AGE,SOCSTATUS_WORK_FL,SOCSTATUS_PENS_FL,GENDER,EDUCATION,MARITAL_STATUS,PERSONAL_INCOME,OWN_AUTO,LOAN_MAX_DLQ_AMT
0,0,49,1,0,1,Среднее специальное,Состою в браке,5000.0,0,1580.00
1,0,32,1,0,1,Среднее,Состою в браке,12000.0,0,4020.00
2,0,52,1,0,1,Неполное среднее,Состою в браке,9000.0,0,0.00
3,0,39,1,0,1,Высшее,Состою в браке,25000.0,0,1590.00
4,0,30,1,0,0,Среднее,Состою в браке,12000.0,0,2230.00
5,0,29,1,0,0,Среднее,Гражданский брак,12000.0,1,0.00
6,0,35,1,0,0,Высшее,Разведен(а),15000.0,0,0.00
7,0,41,1,0,1,Среднее,Состою в браке,6000.0,0,0.00
8,0,53,1,0,0,Высшее,Состою в браке,100000.0,0,0.00
9,0,43,1,0,1,Среднее специальное,Состою в браке,7000.0,0,0.00
10,0,54,1,0,1,Среднее специальное,Не состоял в браке,19000.0,0,0.00
11,1,26,1,0,0,Среднее специальное,Не состоял в браке,18000.0,0,0.00
12,1,62,0,1,0,Среднее,Гражданский брак,7000.0,1,0.00
13,0,45,1,0,1,Среднее специальное,Разведен(а),12000.0,0,810.00
14,0,38,1,0,1,Высшее,Состою в браке,20000.0,0,0.00
15,1,41,1,0,1,Высшее,Разведен(а),60000.0,0,0.00
16,0,65,0,1,1,Среднее специальное,Состою в браке,10000.0,0,0.00
17,0,29,1,0,1,Среднее специальное,Состою в браке,5200.0,0,0.00
18,1,34,1,0,0,Среднее,Гражданский брак,35000.0,0,1439.94
19,0,28,1,0,1,Высшее,Не состоял в браке,15000.0,0,0.00
20,0,37,1,0,1,Высшее,Состою в браке,10000.0,0,0.00
21,0,42,1,0,1,Среднее специальное,Состою в браке,10000.0,0,0.00
22,0,45,1,0,1,Высшее,Разведен(а),14000.0,0,0.00
23,0,32,1,0,1,Среднее специальное,Не состоял в браке,10000.0,1,0.00
24,0,33,1,0,1,Среднее специальное,Состою в браке,8000.0,0,0.00
25,0,38,1,0,1,Среднее специальное,Не состоял в браке,13000.0,0,2742.25
26,0,27,1,0,1,Высшее,Состою в браке,12500.0,1,1411.31
27,1,31,1,0,1,Среднее специальное,Состою в браке,12000.0,0,5760.00
28,0,40,1,0,0,Среднее специальное,Состою в браке,20000.0,0,0.00
29,0,63,0,1,1,Среднее специальное,Состою в браке,5000.0,0,0.00
...,...,...,...,...,...,...,...,...,...,...
15193,0,36,1,0,1,Высшее,Состою в браке,12000.0,0,0.00
15194,0,49,1,0,1,Среднее,Состою в браке,10000.0,0,0.00
15195,0,51,1,1,1,Среднее,Состою в браке,10000.0,0,0.00
15196,0,64,0,1,1,Среднее,Вдовец/Вдова,8000.0,0,0.00
15197,0,61,0,1,1,Среднее специальное,Вдовец/Вдова,11000.0,0,0.00
15198,0,49,1,0,1,Среднее специальное,Состою в браке,7000.0,0,0.00
15199,0,28,1,0,0,Среднее,Состою в браке,10000.0,0,0.00
15200,1,34,1,0,0,Среднее,Состою в браке,8000.0,0,605.59
15201,0,56,1,1,1,Высшее,Состою в браке,25000.0,0,0.00
15202,0,34,1,0,1,Среднее специальное,Состою в браке,10000.0,0,0.00
15203,0,40,1,0,1,Среднее специальное,Состою в браке,12000.0,0,0.00
15204,1,43,1,0,0,Среднее,Состою в браке,7000.0,0,0.00
15205,0,33,1,0,1,Высшее,Состою в браке,12000.0,0,0.00
15206,0,56,1,0,1,Среднее,Вдовец/Вдова,14500.0,0,0.00
15207,0,25,1,0,1,Среднее,Не состоял в браке,12000.0,0,0.00
15208,0,37,1,0,1,Среднее специальное,Состою в браке,8000.0,0,0.00
15209,1,48,1,0,1,Среднее специальное,Не состоял в браке,7000.0,0,0.00
15210,0,30,1,0,1,Среднее специальное,Состою в браке,10000.0,0,0.00
15211,0,35,1,0,1,Высшее,Состою в браке,10000.0,0,0.00
15212,0,55,1,0,0,Среднее,Состою в браке,10000.0,1,0.00
15213,1,36,1,0,0,Среднее,Состою в браке,15000.0,0,0.00
15214,0,31,1,0,1,Высшее,Состою в браке,8100.0,0,0.00
15215,0,35,1,0,1,Среднее специальное,Состою в браке,9500.0,1,0.00
15216,0,61,1,0,0,Среднее,Не состоял в браке,13000.0,1,3300.00
15217,0,39,1,0,1,Среднее специальное,Состою в браке,10000.0,0,0.00
15218,0,25,1,0,0,Среднее,Состою в браке,12000.0,0,0.00
15219,0,51,1,0,1,Среднее специальное,Состою в браке,10000.0,0,0.00
15220,0,22,1,0,1,Среднее,Не состоял в браке,6000.0,0,0.00
15221,0,60,0,1,1,Среднее,Вдовец/Вдова,4500.0,0,0.00
15222,0,37,1,0,0,Среднее,Состою в браке,20000.0,0,0.00

Можно управлять режимом удаления и удалять например ТОЛЬКО те строки или столбцы где все элементы - пустые. Это делает how='all'

In [41]:
df.dropna(how='all')

,TARGET,AGE,SOCSTATUS_WORK_FL,SOCSTATUS_PENS_FL,GENDER,EDUCATION,MARITAL_STATUS,ORG_TP_STATE,JOB_DIR,PERSONAL_INCOME,OWN_AUTO,WORK_TIME,LOAN_MAX_DLQ_AMT
0,0,49,1,0,1,Среднее специальное,Состою в браке,Частная компания,Вспомогательный техперсонал,5000.0,0,18.0,1580.00
1,0,32,1,0,1,Среднее,Состою в браке,Индивидуальный предприниматель,Участие в основ. деятельности,12000.0,0,97.0,4020.00
2,0,52,1,0,1,Неполное среднее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,9000.0,0,84.0,0.00
3,0,39,1,0,1,Высшее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,25000.0,0,168.0,1590.00
4,0,30,1,0,0,Среднее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,12000.0,0,101.0,2230.00
5,0,29,1,0,0,Среднее,Гражданский брак,Частная компания,Адм-хоз. и трансп. службы,12000.0,1,40.0,0.00
6,0,35,1,0,0,Высшее,Разведен(а),Государственная комп./учреж.,Участие в основ. деятельности,15000.0,0,6.0,0.00
7,0,41,1,0,1,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,6000.0,0,6.0,0.00
8,0,53,1,0,0,Высшее,Состою в браке,Частная компания,Участие в основ. деятельности,100000.0,0,156.0,0.00
9,0,43,1,0,1,Среднее специальное,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,7000.0,0,72.0,0.00
10,0,54,1,0,1,Среднее специальное,Не состоял в браке,Государственная комп./учреж.,Пр-техн. обесп. и телеком.,19000.0,0,120.0,0.00
11,1,26,1,0,0,Среднее специальное,Не состоял в браке,Государственная комп./учреж.,Участие в основ. деятельности,18000.0,0,27.0,0.00
12,1,62,0,1,0,Среднее,Гражданский брак,Частная компания,Участие в основ. деятельности,7000.0,1,48.0,0.00
13,0,45,1,0,1,Среднее специальное,Разведен(а),Государственная комп./учреж.,Служба безопасности,12000.0,0,72.0,810.00
14,0,38,1,0,1,Высшее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,20000.0,0,120.0,0.00
15,1,41,1,0,1,Высшее,Разведен(а),Индивидуальный предприниматель,Участие в основ. деятельности,60000.0,0,168.0,0.00
16,0,65,0,1,1,Среднее специальное,Состою в браке,NaN,NaN,10000.0,0,NaN,0.00
17,0,29,1,0,1,Среднее специальное,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,5200.0,0,8.0,0.00
18,1,34,1,0,0,Среднее,Гражданский брак,Частная компания,Участие в основ. деятельности,35000.0,0,13.0,1439.94
19,0,28,1,0,1,Высшее,Не состоял в браке,Частная компания,Участие в основ. деятельности,15000.0,0,60.0,0.00
20,0,37,1,0,1,Высшее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,10000.0,0,192.0,0.00
21,0,42,1,0,1,Среднее специальное,Состою в браке,Частная компания,Участие в основ. деятельности,10000.0,0,76.0,0.00
22,0,45,1,0,1,Высшее,Разведен(а),Государственная комп./учреж.,Участие в основ. деятельности,14000.0,0,120.0,0.00
23,0,32,1,0,1,Среднее специальное,Не состоял в браке,Государственная комп./учреж.,Участие в основ. деятельности,10000.0,1,108.0,0.00
24,0,33,1,0,1,Среднее специальное,Состою в браке,Индивидуальный предприниматель,Участие в основ. деятельности,8000.0,0,24.0,0.00
25,0,38,1,0,1,Среднее специальное,Не состоял в браке,Индивидуальный предприниматель,Участие в основ. деятельности,13000.0,0,18.0,2742.25
26,0,27,1,0,1,Высшее,Состою в браке,Частная компания,Участие в основ. деятельности,12500.0,1,60.0,1411.31
27,1,31,1,0,1,Среднее специальное,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,12000.0,0,15.0,5760.00
28,0,40,1,0,0,Среднее специальное,Состою в браке,Частная компания,Участие в основ. деятельности,20000.0,0,2.0,0.00
29,0,63,0,1,1,Среднее специальное,Состою в браке,NaN,NaN,5000.0,0,NaN,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15193,0,36,1,0,1,Высшее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,12000.0,0,204.0,0.00
15194,0,49,1,0,1,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,10000.0,0,36.0,0.00
15195,0,51,1,1,1,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,10000.0,0,360.0,0.00
15196,0,64,0,1,1,Среднее,Вдовец/Вдова,NaN,NaN,8000.0,0,NaN,0.00
15197,0,61,0,1,1,Среднее специальное,Вдовец/Вдова,NaN,NaN,11000.0,0,NaN,0.00
15198,0,49,1,0,1,Среднее специальное,Состою в браке,Индивидуальный предприниматель,Участие в основ. деятельности,7000.0,0,72.0,0.00
15199,0,28,1,0,0,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,10000.0,0,18.0,0.00
15200,1,34,1,0,0,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,8000.0,0,36.0,605.59
15201,0,56,1,1,1,Высшее,Состою в браке,Частная компания,Участие в основ. деятельности,25000.0,0,84.0,0.00
15202,0,34,1,0,1,Среднее специальное,Состою в браке,Частная компания,Снабжение и сбыт,10000.0,0,7.0,0.00
15203,0,40,1,0,1,Среднее специальное,Состою в браке,Частная компания,Снабжение и сбыт,12000.0,0,8.0,0.00
15204,1,43,1,0,0,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,7000.0,0,27.0,0.00
15205,0,33,1,0,1,Высшее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,12000.0,0,160.0,0.00
15206,0,56,1,0,1,Среднее,Вдовец/Вдова,Частная компания,Участие в основ. деятельности,14500.0,0,384.0,0.00
15207,0,25,1,0,1,Среднее,Не состоял в браке,Индивидуальный предприниматель,Участие в основ. деятельности,12000.0,0,24.0,0.00
15208,0,37,1,0,1,Среднее специальное,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,8000.0,0,60.0,0.00
15209,1,48,1,0,1,Среднее специальное,Не состоял в браке,Частная компания,Участие в основ. деятельности,7000.0,0,6.0,0.00
15210,0,30,1,0,1,Среднее специальное,Состою в браке,Индивидуальный предприниматель,Участие в основ. деятельности,10000.0,0,12.0,0.00
15211,0,35,1,0,1,Высшее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,10000.0,0,48.0,0.00
15212,0,55,1,0,0,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,10000.0,1,204.0,0.00
15213,1,36,1,0,0,Среднее,Состою в браке,Частная компания,Вспомогательный техперсонал,15000.0,0,48.0,0.00
15214,0,31,1,0,1,Высшее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,8100.0,0,96.0,0.00
15215,0,35,1,0,1,Среднее специальное,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,9500.0,1,120.0,0.00
15216,0,61,1,0,0,Среднее,Не состоял в браке,Частная компания,Участие в основ. деятельности,13000.0,1,132.0,3300.00
15217,0,39,1,0,1,Среднее специальное,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,10000.0,0,108.0,0.00
15218,0,25,1,0,0,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,12000.0,0,48.0,0.00
15219,0,51,1,0,1,Среднее специальное,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,10000.0,0,156.0,0.00
15220,0,22,1,0,1,Среднее,Не состоял в браке,Индивидуальный предприниматель,Кадровая служба и секретариат,6000.0,0,48.0,0.00
15221,0,60,0,1,1,Среднее,Вдовец/Вдова,NaN,NaN,4500.0,0,NaN,0.00
15222,0,37,1,0,0,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,20000.0,0,36.0,0.00

## 1.2 Заполнение пустых значений

In [44]:
trash = pd.Series(['1', '2', None, '4', np.nan])
trash

0       1
1       2
2    None
3       4
4     NaN
dtype: object

Для заполнения пустых значений чаще всего используют метод fillna() - он позволяет как заменить каким-то одним значением, так и обработать по алгоритму какие-то пустые значения

In [46]:
trash = trash.fillna(0)
trash

0    1
1    2
2    0
3    4
4    0
dtype: object

In [48]:
df = pd.read_csv('marketing_eng.csv')
df

,TARGET,AGE,SOCSTATUS_WORK_FL,SOCSTATUS_PENS_FL,GENDER,EDUCATION,MARITAL_STATUS,ORG_TP_STATE,JOB_DIR,PERSONAL_INCOME,OWN_AUTO,WORK_TIME,LOAN_MAX_DLQ_AMT
0,0,49,1,0,1,Среднее специальное,Состою в браке,Частная компания,Вспомогательный техперсонал,5000.0,0,18.0,1580.00
1,0,32,1,0,1,Среднее,Состою в браке,Индивидуальный предприниматель,Участие в основ. деятельности,12000.0,0,97.0,4020.00
2,0,52,1,0,1,Неполное среднее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,9000.0,0,84.0,0.00
3,0,39,1,0,1,Высшее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,25000.0,0,168.0,1590.00
4,0,30,1,0,0,Среднее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,12000.0,0,101.0,2230.00
5,0,29,1,0,0,Среднее,Гражданский брак,Частная компания,Адм-хоз. и трансп. службы,12000.0,1,40.0,0.00
6,0,35,1,0,0,Высшее,Разведен(а),Государственная комп./учреж.,Участие в основ. деятельности,15000.0,0,6.0,0.00
7,0,41,1,0,1,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,6000.0,0,6.0,0.00
8,0,53,1,0,0,Высшее,Состою в браке,Частная компания,Участие в основ. деятельности,100000.0,0,156.0,0.00
9,0,43,1,0,1,Среднее специальное,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,7000.0,0,72.0,0.00
10,0,54,1,0,1,Среднее специальное,Не состоял в браке,Государственная комп./учреж.,Пр-техн. обесп. и телеком.,19000.0,0,120.0,0.00
11,1,26,1,0,0,Среднее специальное,Не состоял в браке,Государственная комп./учреж.,Участие в основ. деятельности,18000.0,0,27.0,0.00
12,1,62,0,1,0,Среднее,Гражданский брак,Частная компания,Участие в основ. деятельности,7000.0,1,48.0,0.00
13,0,45,1,0,1,Среднее специальное,Разведен(а),Государственная комп./учреж.,Служба безопасности,12000.0,0,72.0,810.00
14,0,38,1,0,1,Высшее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,20000.0,0,120.0,0.00
15,1,41,1,0,1,Высшее,Разведен(а),Индивидуальный предприниматель,Участие в основ. деятельности,60000.0,0,168.0,0.00
16,0,65,0,1,1,Среднее специальное,Состою в браке,NaN,NaN,10000.0,0,NaN,0.00
17,0,29,1,0,1,Среднее специальное,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,5200.0,0,8.0,0.00
18,1,34,1,0,0,Среднее,Гражданский брак,Частная компания,Участие в основ. деятельности,35000.0,0,13.0,1439.94
19,0,28,1,0,1,Высшее,Не состоял в браке,Частная компания,Участие в основ. деятельности,15000.0,0,60.0,0.00
20,0,37,1,0,1,Высшее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,10000.0,0,192.0,0.00
21,0,42,1,0,1,Среднее специальное,Состою в браке,Частная компания,Участие в основ. деятельности,10000.0,0,76.0,0.00
22,0,45,1,0,1,Высшее,Разведен(а),Государственная комп./учреж.,Участие в основ. деятельности,14000.0,0,120.0,0.00
23,0,32,1,0,1,Среднее специальное,Не состоял в браке,Государственная комп./учреж.,Участие в основ. деятельности,10000.0,1,108.0,0.00
24,0,33,1,0,1,Среднее специальное,Состою в браке,Индивидуальный предприниматель,Участие в основ. деятельности,8000.0,0,24.0,0.00
25,0,38,1,0,1,Среднее специальное,Не состоял в браке,Индивидуальный предприниматель,Участие в основ. деятельности,13000.0,0,18.0,2742.25
26,0,27,1,0,1,Высшее,Состою в браке,Частная компания,Участие в основ. деятельности,12500.0,1,60.0,1411.31
27,1,31,1,0,1,Среднее специальное,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,12000.0,0,15.0,5760.00
28,0,40,1,0,0,Среднее специальное,Состою в браке,Частная компания,Участие в основ. деятельности,20000.0,0,2.0,0.00
29,0,63,0,1,1,Среднее специальное,Состою в браке,NaN,NaN,5000.0,0,NaN,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15193,0,36,1,0,1,Высшее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,12000.0,0,204.0,0.00
15194,0,49,1,0,1,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,10000.0,0,36.0,0.00
15195,0,51,1,1,1,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,10000.0,0,360.0,0.00
15196,0,64,0,1,1,Среднее,Вдовец/Вдова,NaN,NaN,8000.0,0,NaN,0.00
15197,0,61,0,1,1,Среднее специальное,Вдовец/Вдова,NaN,NaN,11000.0,0,NaN,0.00
15198,0,49,1,0,1,Среднее специальное,Состою в браке,Индивидуальный предприниматель,Участие в основ. деятельности,7000.0,0,72.0,0.00
15199,0,28,1,0,0,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,10000.0,0,18.0,0.00
15200,1,34,1,0,0,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,8000.0,0,36.0,605.59
15201,0,56,1,1,1,Высшее,Состою в браке,Частная компания,Участие в основ. деятельности,25000.0,0,84.0,0.00
15202,0,34,1,0,1,Среднее специальное,Состою в браке,Частная компания,Снабжение и сбыт,10000.0,0,7.0,0.00
15203,0,40,1,0,1,Среднее специальное,Состою в браке,Частная компания,Снабжение и сбыт,12000.0,0,8.0,0.00
15204,1,43,1,0,0,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,7000.0,0,27.0,0.00
15205,0,33,1,0,1,Высшее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,12000.0,0,160.0,0.00
15206,0,56,1,0,1,Среднее,Вдовец/Вдова,Частная компания,Участие в основ. деятельности,14500.0,0,384.0,0.00
15207,0,25,1,0,1,Среднее,Не состоял в браке,Индивидуальный предприниматель,Участие в основ. деятельности,12000.0,0,24.0,0.00
15208,0,37,1,0,1,Среднее специальное,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,8000.0,0,60.0,0.00
15209,1,48,1,0,1,Среднее специальное,Не состоял в браке,Частная компания,Участие в основ. деятельности,7000.0,0,6.0,0.00
15210,0,30,1,0,1,Среднее специальное,Состою в браке,Индивидуальный предприниматель,Участие в основ. деятельности,10000.0,0,12.0,0.00
15211,0,35,1,0,1,Высшее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,10000.0,0,48.0,0.00
15212,0,55,1,0,0,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,10000.0,1,204.0,0.00
15213,1,36,1,0,0,Среднее,Состою в браке,Частная компания,Вспомогательный техперсонал,15000.0,0,48.0,0.00
15214,0,31,1,0,1,Высшее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,8100.0,0,96.0,0.00
15215,0,35,1,0,1,Среднее специальное,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,9500.0,1,120.0,0.00
15216,0,61,1,0,0,Среднее,Не состоял в браке,Частная компания,Участие в основ. деятельности,13000.0,1,132.0,3300.00
15217,0,39,1,0,1,Среднее специальное,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,10000.0,0,108.0,0.00
15218,0,25,1,0,0,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,12000.0,0,48.0,0.00
15219,0,51,1,0,1,Среднее специальное,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,10000.0,0,156.0,0.00
15220,0,22,1,0,1,Среднее,Не состоял в браке,Индивидуальный предприниматель,Кадровая служба и секретариат,6000.0,0,48.0,0.00
15221,0,60,0,1,1,Среднее,Вдовец/Вдова,NaN,NaN,4500.0,0,NaN,0.00
15222,0,37,1,0,0,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,20000.0,0,36.0,0.00

Также можно заполнять пропуски в конкретной колонке с использованием своего типа заполняителя для каждой колонки.
Для этого служит конструкция ниже

In [51]:
df.fillna({'JOB_DIR': 'страдаю фигней'})

,TARGET,AGE,SOCSTATUS_WORK_FL,SOCSTATUS_PENS_FL,GENDER,EDUCATION,MARITAL_STATUS,ORG_TP_STATE,JOB_DIR,PERSONAL_INCOME,OWN_AUTO,WORK_TIME,LOAN_MAX_DLQ_AMT
0,0,49,1,0,1,Среднее специальное,Состою в браке,Частная компания,Вспомогательный техперсонал,5000.0,0,18.0,1580.00
1,0,32,1,0,1,Среднее,Состою в браке,Индивидуальный предприниматель,Участие в основ. деятельности,12000.0,0,97.0,4020.00
2,0,52,1,0,1,Неполное среднее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,9000.0,0,84.0,0.00
3,0,39,1,0,1,Высшее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,25000.0,0,168.0,1590.00
4,0,30,1,0,0,Среднее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,12000.0,0,101.0,2230.00
5,0,29,1,0,0,Среднее,Гражданский брак,Частная компания,Адм-хоз. и трансп. службы,12000.0,1,40.0,0.00
6,0,35,1,0,0,Высшее,Разведен(а),Государственная комп./учреж.,Участие в основ. деятельности,15000.0,0,6.0,0.00
7,0,41,1,0,1,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,6000.0,0,6.0,0.00
8,0,53,1,0,0,Высшее,Состою в браке,Частная компания,Участие в основ. деятельности,100000.0,0,156.0,0.00
9,0,43,1,0,1,Среднее специальное,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,7000.0,0,72.0,0.00
10,0,54,1,0,1,Среднее специальное,Не состоял в браке,Государственная комп./учреж.,Пр-техн. обесп. и телеком.,19000.0,0,120.0,0.00
11,1,26,1,0,0,Среднее специальное,Не состоял в браке,Государственная комп./учреж.,Участие в основ. деятельности,18000.0,0,27.0,0.00
12,1,62,0,1,0,Среднее,Гражданский брак,Частная компания,Участие в основ. деятельности,7000.0,1,48.0,0.00
13,0,45,1,0,1,Среднее специальное,Разведен(а),Государственная комп./учреж.,Служба безопасности,12000.0,0,72.0,810.00
14,0,38,1,0,1,Высшее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,20000.0,0,120.0,0.00
15,1,41,1,0,1,Высшее,Разведен(а),Индивидуальный предприниматель,Участие в основ. деятельности,60000.0,0,168.0,0.00
16,0,65,0,1,1,Среднее специальное,Состою в браке,NaN,страдаю фигней,10000.0,0,NaN,0.00
17,0,29,1,0,1,Среднее специальное,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,5200.0,0,8.0,0.00
18,1,34,1,0,0,Среднее,Гражданский брак,Частная компания,Участие в основ. деятельности,35000.0,0,13.0,1439.94
19,0,28,1,0,1,Высшее,Не состоял в браке,Частная компания,Участие в основ. деятельности,15000.0,0,60.0,0.00
20,0,37,1,0,1,Высшее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,10000.0,0,192.0,0.00
21,0,42,1,0,1,Среднее специальное,Состою в браке,Частная компания,Участие в основ. деятельности,10000.0,0,76.0,0.00
22,0,45,1,0,1,Высшее,Разведен(а),Государственная комп./учреж.,Участие в основ. деятельности,14000.0,0,120.0,0.00
23,0,32,1,0,1,Среднее специальное,Не состоял в браке,Государственная комп./учреж.,Участие в основ. деятельности,10000.0,1,108.0,0.00
24,0,33,1,0,1,Среднее специальное,Состою в браке,Индивидуальный предприниматель,Участие в основ. деятельности,8000.0,0,24.0,0.00
25,0,38,1,0,1,Среднее специальное,Не состоял в браке,Индивидуальный предприниматель,Участие в основ. деятельности,13000.0,0,18.0,2742.25
26,0,27,1,0,1,Высшее,Состою в браке,Частная компания,Участие в основ. деятельности,12500.0,1,60.0,1411.31
27,1,31,1,0,1,Среднее специальное,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,12000.0,0,15.0,5760.00
28,0,40,1,0,0,Среднее специальное,Состою в браке,Частная компания,Участие в основ. деятельности,20000.0,0,2.0,0.00
29,0,63,0,1,1,Среднее специальное,Состою в браке,NaN,страдаю фигней,5000.0,0,NaN,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15193,0,36,1,0,1,Высшее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,12000.0,0,204.0,0.00
15194,0,49,1,0,1,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,10000.0,0,36.0,0.00
15195,0,51,1,1,1,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,10000.0,0,360.0,0.00
15196,0,64,0,1,1,Среднее,Вдовец/Вдова,NaN,страдаю фигней,8000.0,0,NaN,0.00
15197,0,61,0,1,1,Среднее специальное,Вдовец/Вдова,NaN,страдаю фигней,11000.0,0,NaN,0.00
15198,0,49,1,0,1,Среднее специальное,Состою в браке,Индивидуальный предприниматель,Участие в основ. деятельности,7000.0,0,72.0,0.00
15199,0,28,1,0,0,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,10000.0,0,18.0,0.00
15200,1,34,1,0,0,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,8000.0,0,36.0,605.59
15201,0,56,1,1,1,Высшее,Состою в браке,Частная компания,Участие в основ. деятельности,25000.0,0,84.0,0.00
15202,0,34,1,0,1,Среднее специальное,Состою в браке,Частная компания,Снабжение и сбыт,10000.0,0,7.0,0.00
15203,0,40,1,0,1,Среднее специальное,Состою в браке,Частная компания,Снабжение и сбыт,12000.0,0,8.0,0.00
15204,1,43,1,0,0,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,7000.0,0,27.0,0.00
15205,0,33,1,0,1,Высшее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,12000.0,0,160.0,0.00
15206,0,56,1,0,1,Среднее,Вдовец/Вдова,Частная компания,Участие в основ. деятельности,14500.0,0,384.0,0.00
15207,0,25,1,0,1,Среднее,Не состоял в браке,Индивидуальный предприниматель,Участие в основ. деятельности,12000.0,0,24.0,0.00
15208,0,37,1,0,1,Среднее специальное,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,8000.0,0,60.0,0.00
15209,1,48,1,0,1,Среднее специальное,Не состоял в браке,Частная компания,Участие в основ. деятельности,7000.0,0,6.0,0.00
15210,0,30,1,0,1,Среднее специальное,Состою в браке,Индивидуальный предприниматель,Участие в основ. деятельности,10000.0,0,12.0,0.00
15211,0,35,1,0,1,Высшее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,10000.0,0,48.0,0.00
15212,0,55,1,0,0,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,10000.0,1,204.0,0.00
15213,1,36,1,0,0,Среднее,Состою в браке,Частная компания,Вспомогательный техперсонал,15000.0,0,48.0,0.00
15214,0,31,1,0,1,Высшее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,8100.0,0,96.0,0.00
15215,0,35,1,0,1,Среднее специальное,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,9500.0,1,120.0,0.00
15216,0,61,1,0,0,Среднее,Не состоял в браке,Частная компания,Участие в основ. деятельности,13000.0,1,132.0,3300.00
15217,0,39,1,0,1,Среднее специальное,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,10000.0,0,108.0,0.00
15218,0,25,1,0,0,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,12000.0,0,48.0,0.00
15219,0,51,1,0,1,Среднее специальное,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,10000.0,0,156.0,0.00
15220,0,22,1,0,1,Среднее,Не состоял в браке,Индивидуальный предприниматель,Кадровая служба и секретариат,6000.0,0,48.0,0.00
15221,0,60,0,1,1,Среднее,Вдовец/Вдова,NaN,страдаю фигней,4500.0,0,NaN,0.00
15222,0,37,1,0,0,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,20000.0,0,36.0,0.00

In [61]:
trash = pd.Series([1, 2, np.nan, 4, np.nan])

Таже можно заполнять используя функции аггрегации (например, среднее)

In [65]:
trash.fillna(trash.mean())

0    1.000000
1    2.000000
2    2.333333
3    4.000000
4    2.333333
dtype: float64

In [66]:
df.fillna({'JOB_DIR': df.PERSONAL_INCOME.mean()})

,TARGET,AGE,SOCSTATUS_WORK_FL,SOCSTATUS_PENS_FL,GENDER,EDUCATION,MARITAL_STATUS,ORG_TP_STATE,JOB_DIR,PERSONAL_INCOME,OWN_AUTO,WORK_TIME,LOAN_MAX_DLQ_AMT
0,0,49,1,0,1,Среднее специальное,Состою в браке,Частная компания,Вспомогательный техперсонал,5000.0,0,18.0,1580.00
1,0,32,1,0,1,Среднее,Состою в браке,Индивидуальный предприниматель,Участие в основ. деятельности,12000.0,0,97.0,4020.00
2,0,52,1,0,1,Неполное среднее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,9000.0,0,84.0,0.00
3,0,39,1,0,1,Высшее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,25000.0,0,168.0,1590.00
4,0,30,1,0,0,Среднее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,12000.0,0,101.0,2230.00
5,0,29,1,0,0,Среднее,Гражданский брак,Частная компания,Адм-хоз. и трансп. службы,12000.0,1,40.0,0.00
6,0,35,1,0,0,Высшее,Разведен(а),Государственная комп./учреж.,Участие в основ. деятельности,15000.0,0,6.0,0.00
7,0,41,1,0,1,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,6000.0,0,6.0,0.00
8,0,53,1,0,0,Высшее,Состою в браке,Частная компания,Участие в основ. деятельности,100000.0,0,156.0,0.00
9,0,43,1,0,1,Среднее специальное,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,7000.0,0,72.0,0.00
10,0,54,1,0,1,Среднее специальное,Не состоял в браке,Государственная комп./учреж.,Пр-техн. обесп. и телеком.,19000.0,0,120.0,0.00
11,1,26,1,0,0,Среднее специальное,Не состоял в браке,Государственная комп./учреж.,Участие в основ. деятельности,18000.0,0,27.0,0.00
12,1,62,0,1,0,Среднее,Гражданский брак,Частная компания,Участие в основ. деятельности,7000.0,1,48.0,0.00
13,0,45,1,0,1,Среднее специальное,Разведен(а),Государственная комп./учреж.,Служба безопасности,12000.0,0,72.0,810.00
14,0,38,1,0,1,Высшее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,20000.0,0,120.0,0.00
15,1,41,1,0,1,Высшее,Разведен(а),Индивидуальный предприниматель,Участие в основ. деятельности,60000.0,0,168.0,0.00
16,0,65,0,1,1,Среднее специальное,Состою в браке,NaN,13853.8,10000.0,0,NaN,0.00
17,0,29,1,0,1,Среднее специальное,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,5200.0,0,8.0,0.00
18,1,34,1,0,0,Среднее,Гражданский брак,Частная компания,Участие в основ. деятельности,35000.0,0,13.0,1439.94
19,0,28,1,0,1,Высшее,Не состоял в браке,Частная компания,Участие в основ. деятельности,15000.0,0,60.0,0.00
20,0,37,1,0,1,Высшее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,10000.0,0,192.0,0.00
21,0,42,1,0,1,Среднее специальное,Состою в браке,Частная компания,Участие в основ. деятельности,10000.0,0,76.0,0.00
22,0,45,1,0,1,Высшее,Разведен(а),Государственная комп./учреж.,Участие в основ. деятельности,14000.0,0,120.0,0.00
23,0,32,1,0,1,Среднее специальное,Не состоял в браке,Государственная комп./учреж.,Участие в основ. деятельности,10000.0,1,108.0,0.00
24,0,33,1,0,1,Среднее специальное,Состою в браке,Индивидуальный предприниматель,Участие в основ. деятельности,8000.0,0,24.0,0.00
25,0,38,1,0,1,Среднее специальное,Не состоял в браке,Индивидуальный предприниматель,Участие в основ. деятельности,13000.0,0,18.0,2742.25
26,0,27,1,0,1,Высшее,Состою в браке,Частная компания,Участие в основ. деятельности,12500.0,1,60.0,1411.31
27,1,31,1,0,1,Среднее специальное,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,12000.0,0,15.0,5760.00
28,0,40,1,0,0,Среднее специальное,Состою в браке,Частная компания,Участие в основ. деятельности,20000.0,0,2.0,0.00
29,0,63,0,1,1,Среднее специальное,Состою в браке,NaN,13853.8,5000.0,0,NaN,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15193,0,36,1,0,1,Высшее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,12000.0,0,204.0,0.00
15194,0,49,1,0,1,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,10000.0,0,36.0,0.00
15195,0,51,1,1,1,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,10000.0,0,360.0,0.00
15196,0,64,0,1,1,Среднее,Вдовец/Вдова,NaN,13853.8,8000.0,0,NaN,0.00
15197,0,61,0,1,1,Среднее специальное,Вдовец/Вдова,NaN,13853.8,11000.0,0,NaN,0.00
15198,0,49,1,0,1,Среднее специальное,Состою в браке,Индивидуальный предприниматель,Участие в основ. деятельности,7000.0,0,72.0,0.00
15199,0,28,1,0,0,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,10000.0,0,18.0,0.00
15200,1,34,1,0,0,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,8000.0,0,36.0,605.59
15201,0,56,1,1,1,Высшее,Состою в браке,Частная компания,Участие в основ. деятельности,25000.0,0,84.0,0.00
15202,0,34,1,0,1,Среднее специальное,Состою в браке,Частная компания,Снабжение и сбыт,10000.0,0,7.0,0.00
15203,0,40,1,0,1,Среднее специальное,Состою в браке,Частная компания,Снабжение и сбыт,12000.0,0,8.0,0.00
15204,1,43,1,0,0,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,7000.0,0,27.0,0.00
15205,0,33,1,0,1,Высшее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,12000.0,0,160.0,0.00
15206,0,56,1,0,1,Среднее,Вдовец/Вдова,Частная компания,Участие в основ. деятельности,14500.0,0,384.0,0.00
15207,0,25,1,0,1,Среднее,Не состоял в браке,Индивидуальный предприниматель,Участие в основ. деятельности,12000.0,0,24.0,0.00
15208,0,37,1,0,1,Среднее специальное,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,8000.0,0,60.0,0.00
15209,1,48,1,0,1,Среднее специальное,Не состоял в браке,Частная компания,Участие в основ. деятельности,7000.0,0,6.0,0.00
15210,0,30,1,0,1,Среднее специальное,Состою в браке,Индивидуальный предприниматель,Участие в основ. деятельности,10000.0,0,12.0,0.00
15211,0,35,1,0,1,Высшее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,10000.0,0,48.0,0.00
15212,0,55,1,0,0,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,10000.0,1,204.0,0.00
15213,1,36,1,0,0,Среднее,Состою в браке,Частная компания,Вспомогательный техперсонал,15000.0,0,48.0,0.00
15214,0,31,1,0,1,Высшее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,8100.0,0,96.0,0.00
15215,0,35,1,0,1,Среднее специальное,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,9500.0,1,120.0,0.00
15216,0,61,1,0,0,Среднее,Не состоял в браке,Частная компания,Участие в основ. деятельности,13000.0,1,132.0,3300.00
15217,0,39,1,0,1,Среднее специальное,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,10000.0,0,108.0,0.00
15218,0,25,1,0,0,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,12000.0,0,48.0,0.00
15219,0,51,1,0,1,Среднее специальное,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,10000.0,0,156.0,0.00
15220,0,22,1,0,1,Среднее,Не состоял в браке,Индивидуальный предприниматель,Кадровая служба и секретариат,6000.0,0,48.0,0.00
15221,0,60,0,1,1,Среднее,Вдовец/Вдова,NaN,13853.8,4500.0,0,NaN,0.00
15222,0,37,1,0,0,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,20000.0,0,36.0,0.00

In [68]:
df.fillna({'JOB_DIR': df.PERSONAL_INCOME.mean()})

,TARGET,AGE,SOCSTATUS_WORK_FL,SOCSTATUS_PENS_FL,GENDER,EDUCATION,MARITAL_STATUS,ORG_TP_STATE,JOB_DIR,PERSONAL_INCOME,OWN_AUTO,WORK_TIME,LOAN_MAX_DLQ_AMT
0,0,49,1,0,1,Среднее специальное,Состою в браке,Частная компания,Вспомогательный техперсонал,5000.0,0,18.0,1580.00
1,0,32,1,0,1,Среднее,Состою в браке,Индивидуальный предприниматель,Участие в основ. деятельности,12000.0,0,97.0,4020.00
2,0,52,1,0,1,Неполное среднее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,9000.0,0,84.0,0.00
3,0,39,1,0,1,Высшее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,25000.0,0,168.0,1590.00
4,0,30,1,0,0,Среднее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,12000.0,0,101.0,2230.00
5,0,29,1,0,0,Среднее,Гражданский брак,Частная компания,Адм-хоз. и трансп. службы,12000.0,1,40.0,0.00
6,0,35,1,0,0,Высшее,Разведен(а),Государственная комп./учреж.,Участие в основ. деятельности,15000.0,0,6.0,0.00
7,0,41,1,0,1,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,6000.0,0,6.0,0.00
8,0,53,1,0,0,Высшее,Состою в браке,Частная компания,Участие в основ. деятельности,100000.0,0,156.0,0.00
9,0,43,1,0,1,Среднее специальное,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,7000.0,0,72.0,0.00
10,0,54,1,0,1,Среднее специальное,Не состоял в браке,Государственная комп./учреж.,Пр-техн. обесп. и телеком.,19000.0,0,120.0,0.00
11,1,26,1,0,0,Среднее специальное,Не состоял в браке,Государственная комп./учреж.,Участие в основ. деятельности,18000.0,0,27.0,0.00
12,1,62,0,1,0,Среднее,Гражданский брак,Частная компания,Участие в основ. деятельности,7000.0,1,48.0,0.00
13,0,45,1,0,1,Среднее специальное,Разведен(а),Государственная комп./учреж.,Служба безопасности,12000.0,0,72.0,810.00
14,0,38,1,0,1,Высшее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,20000.0,0,120.0,0.00
15,1,41,1,0,1,Высшее,Разведен(а),Индивидуальный предприниматель,Участие в основ. деятельности,60000.0,0,168.0,0.00
16,0,65,0,1,1,Среднее специальное,Состою в браке,NaN,13853.8,10000.0,0,NaN,0.00
17,0,29,1,0,1,Среднее специальное,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,5200.0,0,8.0,0.00
18,1,34,1,0,0,Среднее,Гражданский брак,Частная компания,Участие в основ. деятельности,35000.0,0,13.0,1439.94
19,0,28,1,0,1,Высшее,Не состоял в браке,Частная компания,Участие в основ. деятельности,15000.0,0,60.0,0.00
20,0,37,1,0,1,Высшее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,10000.0,0,192.0,0.00
21,0,42,1,0,1,Среднее специальное,Состою в браке,Частная компания,Участие в основ. деятельности,10000.0,0,76.0,0.00
22,0,45,1,0,1,Высшее,Разведен(а),Государственная комп./учреж.,Участие в основ. деятельности,14000.0,0,120.0,0.00
23,0,32,1,0,1,Среднее специальное,Не состоял в браке,Государственная комп./учреж.,Участие в основ. деятельности,10000.0,1,108.0,0.00
24,0,33,1,0,1,Среднее специальное,Состою в браке,Индивидуальный предприниматель,Участие в основ. деятельности,8000.0,0,24.0,0.00
25,0,38,1,0,1,Среднее специальное,Не состоял в браке,Индивидуальный предприниматель,Участие в основ. деятельности,13000.0,0,18.0,2742.25
26,0,27,1,0,1,Высшее,Состою в браке,Частная компания,Участие в основ. деятельности,12500.0,1,60.0,1411.31
27,1,31,1,0,1,Среднее специальное,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,12000.0,0,15.0,5760.00
28,0,40,1,0,0,Среднее специальное,Состою в браке,Частная компания,Участие в основ. деятельности,20000.0,0,2.0,0.00
29,0,63,0,1,1,Среднее специальное,Состою в браке,NaN,13853.8,5000.0,0,NaN,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15193,0,36,1,0,1,Высшее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,12000.0,0,204.0,0.00
15194,0,49,1,0,1,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,10000.0,0,36.0,0.00
15195,0,51,1,1,1,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,10000.0,0,360.0,0.00
15196,0,64,0,1,1,Среднее,Вдовец/Вдова,NaN,13853.8,8000.0,0,NaN,0.00
15197,0,61,0,1,1,Среднее специальное,Вдовец/Вдова,NaN,13853.8,11000.0,0,NaN,0.00
15198,0,49,1,0,1,Среднее специальное,Состою в браке,Индивидуальный предприниматель,Участие в основ. деятельности,7000.0,0,72.0,0.00
15199,0,28,1,0,0,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,10000.0,0,18.0,0.00
15200,1,34,1,0,0,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,8000.0,0,36.0,605.59
15201,0,56,1,1,1,Высшее,Состою в браке,Частная компания,Участие в основ. деятельности,25000.0,0,84.0,0.00
15202,0,34,1,0,1,Среднее специальное,Состою в браке,Частная компания,Снабжение и сбыт,10000.0,0,7.0,0.00
15203,0,40,1,0,1,Среднее специальное,Состою в браке,Частная компания,Снабжение и сбыт,12000.0,0,8.0,0.00
15204,1,43,1,0,0,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,7000.0,0,27.0,0.00
15205,0,33,1,0,1,Высшее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,12000.0,0,160.0,0.00
15206,0,56,1,0,1,Среднее,Вдовец/Вдова,Частная компания,Участие в основ. деятельности,14500.0,0,384.0,0.00
15207,0,25,1,0,1,Среднее,Не состоял в браке,Индивидуальный предприниматель,Участие в основ. деятельности,12000.0,0,24.0,0.00
15208,0,37,1,0,1,Среднее специальное,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,8000.0,0,60.0,0.00
15209,1,48,1,0,1,Среднее специальное,Не состоял в браке,Частная компания,Участие в основ. деятельности,7000.0,0,6.0,0.00
15210,0,30,1,0,1,Среднее специальное,Состою в браке,Индивидуальный предприниматель,Участие в основ. деятельности,10000.0,0,12.0,0.00
15211,0,35,1,0,1,Высшее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,10000.0,0,48.0,0.00
15212,0,55,1,0,0,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,10000.0,1,204.0,0.00
15213,1,36,1,0,0,Среднее,Состою в браке,Частная компания,Вспомогательный техперсонал,15000.0,0,48.0,0.00
15214,0,31,1,0,1,Высшее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,8100.0,0,96.0,0.00
15215,0,35,1,0,1,Среднее специальное,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,9500.0,1,120.0,0.00
15216,0,61,1,0,0,Среднее,Не состоял в браке,Частная компания,Участие в основ. деятельности,13000.0,1,132.0,3300.00
15217,0,39,1,0,1,Среднее специальное,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,10000.0,0,108.0,0.00
15218,0,25,1,0,0,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,12000.0,0,48.0,0.00
15219,0,51,1,0,1,Среднее специальное,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,10000.0,0,156.0,0.00
15220,0,22,1,0,1,Среднее,Не состоял в браке,Индивидуальный предприниматель,Кадровая служба и секретариат,6000.0,0,48.0,0.00
15221,0,60,0,1,1,Среднее,Вдовец/Вдова,NaN,13853.8,4500.0,0,NaN,0.00
15222,0,37,1,0,0,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,20000.0,0,36.0,0.00

In [3]:
trash = pd.Series([1, 2, np.nan, 4, 5])
trash

0    1.0
1    2.0
2    NaN
3    4.0
4    5.0
dtype: float64

In [4]:
trash.interpolate()

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
dtype: float64

## 1.3 Преобразования данных

### Удаление дубликатов

In [77]:
duble = pd.Series(['первый', 'второй', 'третий', 'первый', 'третий'])
duble

0    первый
1    второй
2    третий
3    первый
4    третий
dtype: object

In [78]:
duble.drop_duplicates()

0    первый
1    второй
2    третий
dtype: object

In [79]:
df = pd.read_csv('marketing_eng.csv')

In [86]:
df.drop_duplicates('MARITAL_STATUS')

,TARGET,AGE,SOCSTATUS_WORK_FL,SOCSTATUS_PENS_FL,GENDER,EDUCATION,MARITAL_STATUS,ORG_TP_STATE,JOB_DIR,PERSONAL_INCOME,OWN_AUTO,WORK_TIME,LOAN_MAX_DLQ_AMT
0,0,49,1,0,1,Среднее специальное,Состою в браке,Частная компания,Вспомогательный техперсонал,5000.0,0,18.0,1580.0
5,0,29,1,0,0,Среднее,Гражданский брак,Частная компания,Адм-хоз. и трансп. службы,12000.0,1,40.0,0.0
6,0,35,1,0,0,Высшее,Разведен(а),Государственная комп./учреж.,Участие в основ. деятельности,15000.0,0,6.0,0.0
10,0,54,1,0,1,Среднее специальное,Не состоял в браке,Государственная комп./учреж.,Пр-техн. обесп. и телеком.,19000.0,0,120.0,0.0
47,0,48,1,0,1,Высшее,Вдовец/Вдова,Государственная комп./учреж.,Участие в основ. деятельности,15000.0,0,132.0,0.0

In [87]:
df.drop_duplicates(subset={'MARITAL_STATUS', 'ORG_TP_STATE'})

,TARGET,AGE,SOCSTATUS_WORK_FL,SOCSTATUS_PENS_FL,GENDER,EDUCATION,MARITAL_STATUS,ORG_TP_STATE,JOB_DIR,PERSONAL_INCOME,OWN_AUTO,WORK_TIME,LOAN_MAX_DLQ_AMT
0,0,49,1,0,1,Среднее специальное,Состою в браке,Частная компания,Вспомогательный техперсонал,5000.0,0,18.0,1580.00
1,0,32,1,0,1,Среднее,Состою в браке,Индивидуальный предприниматель,Участие в основ. деятельности,12000.0,0,97.0,4020.00
2,0,52,1,0,1,Неполное среднее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,9000.0,0,84.0,0.00
5,0,29,1,0,0,Среднее,Гражданский брак,Частная компания,Адм-хоз. и трансп. службы,12000.0,1,40.0,0.00
6,0,35,1,0,0,Высшее,Разведен(а),Государственная комп./учреж.,Участие в основ. деятельности,15000.0,0,6.0,0.00
10,0,54,1,0,1,Среднее специальное,Не состоял в браке,Государственная комп./учреж.,Пр-техн. обесп. и телеком.,19000.0,0,120.0,0.00
15,1,41,1,0,1,Высшее,Разведен(а),Индивидуальный предприниматель,Участие в основ. деятельности,60000.0,0,168.0,0.00
16,0,65,0,1,1,Среднее специальное,Состою в браке,NaN,NaN,10000.0,0,NaN,0.00
19,0,28,1,0,1,Высшее,Не состоял в браке,Частная компания,Участие в основ. деятельности,15000.0,0,60.0,0.00
25,0,38,1,0,1,Среднее специальное,Не состоял в браке,Индивидуальный предприниматель,Участие в основ. деятельности,13000.0,0,18.0,2742.25
47,0,48,1,0,1,Высшее,Вдовец/Вдова,Государственная комп./учреж.,Участие в основ. деятельности,15000.0,0,132.0,0.00
66,0,44,1,0,0,Неполное среднее,Гражданский брак,Государственная комп./учреж.,Пр-техн. обесп. и телеком.,11000.0,0,108.0,0.00
90,0,56,1,0,0,Среднее специальное,Состою в браке,Некоммерческая организация,Участие в основ. деятельности,4000.0,0,24.0,0.00
107,0,45,1,0,1,Среднее,Не состоял в браке,Некоммерческая организация,Участие в основ. деятельности,5000.0,0,12.0,0.00
125,0,57,0,1,1,Среднее специальное,Вдовец/Вдова,NaN,NaN,8000.0,0,NaN,0.00
140,0,53,1,0,1,Среднее,Разведен(а),Частная компания,Вспомогательный техперсонал,6000.0,0,120.0,0.00
185,0,36,1,0,1,Высшее,Разведен(а),Некоммерческая организация,Участие в основ. деятельности,17000.0,1,60.0,0.00
238,0,42,1,0,1,Среднее специальное,Вдовец/Вдова,Частная компания,Участие в основ. деятельности,25000.0,0,84.0,0.00
263,0,62,0,1,1,Высшее,Не состоял в браке,NaN,NaN,6000.0,0,NaN,0.00
355,0,26,1,0,0,Среднее специальное,Состою в браке,Частная ком. с инос. капиталом,Участие в основ. деятельности,15000.0,0,30.0,0.00
400,1,56,1,0,1,Среднее специальное,Вдовец/Вдова,Частная ком. с инос. капиталом,Участие в основ. деятельности,11000.0,0,48.0,0.00
505,0,60,0,1,1,Среднее специальное,Разведен(а),NaN,NaN,6300.0,0,NaN,0.00
516,0,35,1,0,1,Среднее специальное,Вдовец/Вдова,Индивидуальный предприниматель,Реклама и маркетинг,30000.0,0,36.0,0.00
776,1,29,1,0,0,Среднее специальное,Гражданский брак,Индивидуальный предприниматель,Участие в основ. деятельности,9000.0,0,24.0,0.00
812,0,54,1,0,1,Среднее специальное,Вдовец/Вдова,Некоммерческая организация,Участие в основ. деятельности,15000.0,0,120.0,0.00
1644,0,61,0,1,1,Среднее специальное,Гражданский брак,NaN,NaN,6000.0,0,NaN,0.00
1748,0,22,1,0,0,Среднее специальное,Не состоял в браке,Частная ком. с инос. капиталом,Вспомогательный техперсонал,15000.0,0,12.0,0.00
2112,1,34,1,0,1,Среднее,Гражданский брак,Некоммерческая организация,Участие в основ. деятельности,12000.0,0,48.0,0.00
4865,0,41,1,0,0,Среднее специальное,Гражданский брак,Частная ком. с инос. капиталом,Участие в основ. деятельности,35000.0,1,60.0,0.00
5014,0,22,1,0,1,Неоконченное высшее,Разведен(а),Частная ком. с инос. капиталом,Участие в основ. деятельности,21000.0,0,9.0,1742.41

### Замена значений

In [88]:
df = pd.read_csv('marketing_eng.csv')

In [89]:
df.replace('Среднее специальное', 'UNDERGRADUATE')

,TARGET,AGE,SOCSTATUS_WORK_FL,SOCSTATUS_PENS_FL,GENDER,EDUCATION,MARITAL_STATUS,ORG_TP_STATE,JOB_DIR,PERSONAL_INCOME,OWN_AUTO,WORK_TIME,LOAN_MAX_DLQ_AMT
0,0,49,1,0,1,UNDERGRADUATE,Состою в браке,Частная компания,Вспомогательный техперсонал,5000.0,0,18.0,1580.00
1,0,32,1,0,1,Среднее,Состою в браке,Индивидуальный предприниматель,Участие в основ. деятельности,12000.0,0,97.0,4020.00
2,0,52,1,0,1,Неполное среднее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,9000.0,0,84.0,0.00
3,0,39,1,0,1,Высшее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,25000.0,0,168.0,1590.00
4,0,30,1,0,0,Среднее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,12000.0,0,101.0,2230.00
5,0,29,1,0,0,Среднее,Гражданский брак,Частная компания,Адм-хоз. и трансп. службы,12000.0,1,40.0,0.00
6,0,35,1,0,0,Высшее,Разведен(а),Государственная комп./учреж.,Участие в основ. деятельности,15000.0,0,6.0,0.00
7,0,41,1,0,1,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,6000.0,0,6.0,0.00
8,0,53,1,0,0,Высшее,Состою в браке,Частная компания,Участие в основ. деятельности,100000.0,0,156.0,0.00
9,0,43,1,0,1,UNDERGRADUATE,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,7000.0,0,72.0,0.00
10,0,54,1,0,1,UNDERGRADUATE,Не состоял в браке,Государственная комп./учреж.,Пр-техн. обесп. и телеком.,19000.0,0,120.0,0.00
11,1,26,1,0,0,UNDERGRADUATE,Не состоял в браке,Государственная комп./учреж.,Участие в основ. деятельности,18000.0,0,27.0,0.00
12,1,62,0,1,0,Среднее,Гражданский брак,Частная компания,Участие в основ. деятельности,7000.0,1,48.0,0.00
13,0,45,1,0,1,UNDERGRADUATE,Разведен(а),Государственная комп./учреж.,Служба безопасности,12000.0,0,72.0,810.00
14,0,38,1,0,1,Высшее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,20000.0,0,120.0,0.00
15,1,41,1,0,1,Высшее,Разведен(а),Индивидуальный предприниматель,Участие в основ. деятельности,60000.0,0,168.0,0.00
16,0,65,0,1,1,UNDERGRADUATE,Состою в браке,NaN,NaN,10000.0,0,NaN,0.00
17,0,29,1,0,1,UNDERGRADUATE,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,5200.0,0,8.0,0.00
18,1,34,1,0,0,Среднее,Гражданский брак,Частная компания,Участие в основ. деятельности,35000.0,0,13.0,1439.94
19,0,28,1,0,1,Высшее,Не состоял в браке,Частная компания,Участие в основ. деятельности,15000.0,0,60.0,0.00
20,0,37,1,0,1,Высшее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,10000.0,0,192.0,0.00
21,0,42,1,0,1,UNDERGRADUATE,Состою в браке,Частная компания,Участие в основ. деятельности,10000.0,0,76.0,0.00
22,0,45,1,0,1,Высшее,Разведен(а),Государственная комп./учреж.,Участие в основ. деятельности,14000.0,0,120.0,0.00
23,0,32,1,0,1,UNDERGRADUATE,Не состоял в браке,Государственная комп./учреж.,Участие в основ. деятельности,10000.0,1,108.0,0.00
24,0,33,1,0,1,UNDERGRADUATE,Состою в браке,Индивидуальный предприниматель,Участие в основ. деятельности,8000.0,0,24.0,0.00
25,0,38,1,0,1,UNDERGRADUATE,Не состоял в браке,Индивидуальный предприниматель,Участие в основ. деятельности,13000.0,0,18.0,2742.25
26,0,27,1,0,1,Высшее,Состою в браке,Частная компания,Участие в основ. деятельности,12500.0,1,60.0,1411.31
27,1,31,1,0,1,UNDERGRADUATE,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,12000.0,0,15.0,5760.00
28,0,40,1,0,0,UNDERGRADUATE,Состою в браке,Частная компания,Участие в основ. деятельности,20000.0,0,2.0,0.00
29,0,63,0,1,1,UNDERGRADUATE,Состою в браке,NaN,NaN,5000.0,0,NaN,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15193,0,36,1,0,1,Высшее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,12000.0,0,204.0,0.00
15194,0,49,1,0,1,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,10000.0,0,36.0,0.00
15195,0,51,1,1,1,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,10000.0,0,360.0,0.00
15196,0,64,0,1,1,Среднее,Вдовец/Вдова,NaN,NaN,8000.0,0,NaN,0.00
15197,0,61,0,1,1,UNDERGRADUATE,Вдовец/Вдова,NaN,NaN,11000.0,0,NaN,0.00
15198,0,49,1,0,1,UNDERGRADUATE,Состою в браке,Индивидуальный предприниматель,Участие в основ. деятельности,7000.0,0,72.0,0.00
15199,0,28,1,0,0,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,10000.0,0,18.0,0.00
15200,1,34,1,0,0,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,8000.0,0,36.0,605.59
15201,0,56,1,1,1,Высшее,Состою в браке,Частная компания,Участие в основ. деятельности,25000.0,0,84.0,0.00
15202,0,34,1,0,1,UNDERGRADUATE,Состою в браке,Частная компания,Снабжение и сбыт,10000.0,0,7.0,0.00
15203,0,40,1,0,1,UNDERGRADUATE,Состою в браке,Частная компания,Снабжение и сбыт,12000.0,0,8.0,0.00
15204,1,43,1,0,0,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,7000.0,0,27.0,0.00
15205,0,33,1,0,1,Высшее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,12000.0,0,160.0,0.00
15206,0,56,1,0,1,Среднее,Вдовец/Вдова,Частная компания,Участие в основ. деятельности,14500.0,0,384.0,0.00
15207,0,25,1,0,1,Среднее,Не состоял в браке,Индивидуальный предприниматель,Участие в основ. деятельности,12000.0,0,24.0,0.00
15208,0,37,1,0,1,UNDERGRADUATE,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,8000.0,0,60.0,0.00
15209,1,48,1,0,1,UNDERGRADUATE,Не состоял в браке,Частная компания,Участие в основ. деятельности,7000.0,0,6.0,0.00
15210,0,30,1,0,1,UNDERGRADUATE,Состою в браке,Индивидуальный предприниматель,Участие в основ. деятельности,10000.0,0,12.0,0.00
15211,0,35,1,0,1,Высшее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,10000.0,0,48.0,0.00
15212,0,55,1,0,0,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,10000.0,1,204.0,0.00
15213,1,36,1,0,0,Среднее,Состою в браке,Частная компания,Вспомогательный техперсонал,15000.0,0,48.0,0.00
15214,0,31,1,0,1,Высшее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,8100.0,0,96.0,0.00
15215,0,35,1,0,1,UNDERGRADUATE,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,9500.0,1,120.0,0.00
15216,0,61,1,0,0,Среднее,Не состоял в браке,Частная компания,Участие в основ. деятельности,13000.0,1,132.0,3300.00
15217,0,39,1,0,1,UNDERGRADUATE,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,10000.0,0,108.0,0.00
15218,0,25,1,0,0,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,12000.0,0,48.0,0.00
15219,0,51,1,0,1,UNDERGRADUATE,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,10000.0,0,156.0,0.00
15220,0,22,1,0,1,Среднее,Не состоял в браке,Индивидуальный предприниматель,Кадровая служба и секретариат,6000.0,0,48.0,0.00
15221,0,60,0,1,1,Среднее,Вдовец/Вдова,NaN,NaN,4500.0,0,NaN,0.00
15222,0,37,1,0,0,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,20000.0,0,36.0,0.00

In [96]:
df.GENDER = df.GENDER.replace({0: 'male', 1: 'female'})
df

### Дискретизация

In [6]:
df = pd.read_csv('marketing_eng.csv')

Для разбиения данных количественных (или подвергающихся счету) в Pandas существует метод cut. Он разделяет количественную переменную на т.н. bin's - интеравалы некой заданной длинны, которые представляю собой категориальные переменные

In [99]:
df.AGE.describe()

count    15223.000000
mean        40.406096
std         11.601068
min         21.000000
25%         30.000000
50%         39.000000
75%         50.000000
max         67.000000
Name: AGE, dtype: float64

Давайте разобъем данную переменную на заданные интервалы

In [100]:
pd.cut(df.AGE, [20,30,40,50,60,70,80,90])

0        (40, 50]
1        (30, 40]
2        (50, 60]
3        (30, 40]
4        (20, 30]
5        (20, 30]
6        (30, 40]
7        (40, 50]
8        (50, 60]
9        (40, 50]
10       (50, 60]
11       (20, 30]
12       (60, 70]
13       (40, 50]
14       (30, 40]
15       (40, 50]
16       (60, 70]
17       (20, 30]
18       (30, 40]
19       (20, 30]
20       (30, 40]
21       (40, 50]
22       (40, 50]
23       (30, 40]
24       (30, 40]
25       (30, 40]
26       (20, 30]
27       (30, 40]
28       (30, 40]
29       (60, 70]
           ...
15193    (30, 40]
15194    (40, 50]
15195    (50, 60]
15196    (60, 70]
15197    (60, 70]
15198    (40, 50]
15199    (20, 30]
15200    (30, 40]
15201    (50, 60]
15202    (30, 40]
15203    (30, 40]
15204    (40, 50]
15205    (30, 40]
15206    (50, 60]
15207    (20, 30]
15208    (30, 40]
15209    (40, 50]
15210    (20, 30]
15211    (30, 40]
15212    (50, 60]
15213    (30, 40]
15214    (30, 40]
15215    (30, 40]
15216    (60, 70]
15217    (30, 40]
15218    (20, 30]
15219    (50, 60]
15220    (20, 30]
15221    (50, 60]
15222    (30, 40]
Name: AGE, Length: 15223, dtype: category
Categories (7, interval[int64]): [(20, 30] < (30, 40] < (40, 50] < (50, 60] < (60, 70] < (70, 80] < (80, 90]]

In [108]:
df.AGE = pd.cut(df.AGE, [20,40,60,80,90], labels=['молодые','зрелые','старые','древние как мамонт'])

In [7]:
df

,TARGET,AGE,SOCSTATUS_WORK_FL,SOCSTATUS_PENS_FL,GENDER,EDUCATION,MARITAL_STATUS,ORG_TP_STATE,JOB_DIR,PERSONAL_INCOME,OWN_AUTO,WORK_TIME,LOAN_MAX_DLQ_AMT
0,0,49,1,0,1,Среднее специальное,Состою в браке,Частная компания,Вспомогательный техперсонал,5000.0,0,18.0,1580.00
1,0,32,1,0,1,Среднее,Состою в браке,Индивидуальный предприниматель,Участие в основ. деятельности,12000.0,0,97.0,4020.00
2,0,52,1,0,1,Неполное среднее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,9000.0,0,84.0,0.00
3,0,39,1,0,1,Высшее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,25000.0,0,168.0,1590.00
4,0,30,1,0,0,Среднее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,12000.0,0,101.0,2230.00
5,0,29,1,0,0,Среднее,Гражданский брак,Частная компания,Адм-хоз. и трансп. службы,12000.0,1,40.0,0.00
6,0,35,1,0,0,Высшее,Разведен(а),Государственная комп./учреж.,Участие в основ. деятельности,15000.0,0,6.0,0.00
7,0,41,1,0,1,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,6000.0,0,6.0,0.00
8,0,53,1,0,0,Высшее,Состою в браке,Частная компания,Участие в основ. деятельности,100000.0,0,156.0,0.00
9,0,43,1,0,1,Среднее специальное,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,7000.0,0,72.0,0.00
10,0,54,1,0,1,Среднее специальное,Не состоял в браке,Государственная комп./учреж.,Пр-техн. обесп. и телеком.,19000.0,0,120.0,0.00
11,1,26,1,0,0,Среднее специальное,Не состоял в браке,Государственная комп./учреж.,Участие в основ. деятельности,18000.0,0,27.0,0.00
12,1,62,0,1,0,Среднее,Гражданский брак,Частная компания,Участие в основ. деятельности,7000.0,1,48.0,0.00
13,0,45,1,0,1,Среднее специальное,Разведен(а),Государственная комп./учреж.,Служба безопасности,12000.0,0,72.0,810.00
14,0,38,1,0,1,Высшее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,20000.0,0,120.0,0.00
15,1,41,1,0,1,Высшее,Разведен(а),Индивидуальный предприниматель,Участие в основ. деятельности,60000.0,0,168.0,0.00
16,0,65,0,1,1,Среднее специальное,Состою в браке,NaN,NaN,10000.0,0,NaN,0.00
17,0,29,1,0,1,Среднее специальное,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,5200.0,0,8.0,0.00
18,1,34,1,0,0,Среднее,Гражданский брак,Частная компания,Участие в основ. деятельности,35000.0,0,13.0,1439.94
19,0,28,1,0,1,Высшее,Не состоял в браке,Частная компания,Участие в основ. деятельности,15000.0,0,60.0,0.00
20,0,37,1,0,1,Высшее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,10000.0,0,192.0,0.00
21,0,42,1,0,1,Среднее специальное,Состою в браке,Частная компания,Участие в основ. деятельности,10000.0,0,76.0,0.00
22,0,45,1,0,1,Высшее,Разведен(а),Государственная комп./учреж.,Участие в основ. деятельности,14000.0,0,120.0,0.00
23,0,32,1,0,1,Среднее специальное,Не состоял в браке,Государственная комп./учреж.,Участие в основ. деятельности,10000.0,1,108.0,0.00
24,0,33,1,0,1,Среднее специальное,Состою в браке,Индивидуальный предприниматель,Участие в основ. деятельности,8000.0,0,24.0,0.00
25,0,38,1,0,1,Среднее специальное,Не состоял в браке,Индивидуальный предприниматель,Участие в основ. деятельности,13000.0,0,18.0,2742.25
26,0,27,1,0,1,Высшее,Состою в браке,Частная компания,Участие в основ. деятельности,12500.0,1,60.0,1411.31
27,1,31,1,0,1,Среднее специальное,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,12000.0,0,15.0,5760.00
28,0,40,1,0,0,Среднее специальное,Состою в браке,Частная компания,Участие в основ. деятельности,20000.0,0,2.0,0.00
29,0,63,0,1,1,Среднее специальное,Состою в браке,NaN,NaN,5000.0,0,NaN,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15193,0,36,1,0,1,Высшее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,12000.0,0,204.0,0.00
15194,0,49,1,0,1,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,10000.0,0,36.0,0.00
15195,0,51,1,1,1,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,10000.0,0,360.0,0.00
15196,0,64,0,1,1,Среднее,Вдовец/Вдова,NaN,NaN,8000.0,0,NaN,0.00
15197,0,61,0,1,1,Среднее специальное,Вдовец/Вдова,NaN,NaN,11000.0,0,NaN,0.00
15198,0,49,1,0,1,Среднее специальное,Состою в браке,Индивидуальный предприниматель,Участие в основ. деятельности,7000.0,0,72.0,0.00
15199,0,28,1,0,0,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,10000.0,0,18.0,0.00
15200,1,34,1,0,0,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,8000.0,0,36.0,605.59
15201,0,56,1,1,1,Высшее,Состою в браке,Частная компания,Участие в основ. деятельности,25000.0,0,84.0,0.00
15202,0,34,1,0,1,Среднее специальное,Состою в браке,Частная компания,Снабжение и сбыт,10000.0,0,7.0,0.00
15203,0,40,1,0,1,Среднее специальное,Состою в браке,Частная компания,Снабжение и сбыт,12000.0,0,8.0,0.00
15204,1,43,1,0,0,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,7000.0,0,27.0,0.00
15205,0,33,1,0,1,Высшее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,12000.0,0,160.0,0.00
15206,0,56,1,0,1,Среднее,Вдовец/Вдова,Частная компания,Участие в основ. деятельности,14500.0,0,384.0,0.00
15207,0,25,1,0,1,Среднее,Не состоял в браке,Индивидуальный предприниматель,Участие в основ. деятельности,12000.0,0,24.0,0.00
15208,0,37,1,0,1,Среднее специальное,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,8000.0,0,60.0,0.00
15209,1,48,1,0,1,Среднее специальное,Не состоял в браке,Частная компания,Участие в основ. деятельности,7000.0,0,6.0,0.00
15210,0,30,1,0,1,Среднее специальное,Состою в браке,Индивидуальный предприниматель,Участие в основ. деятельности,10000.0,0,12.0,0.00
15211,0,35,1,0,1,Высшее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,10000.0,0,48.0,0.00
15212,0,55,1,0,0,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,10000.0,1,204.0,0.00
15213,1,36,1,0,0,Среднее,Состою в браке,Частная компания,Вспомогательный техперсонал,15000.0,0,48.0,0.00
15214,0,31,1,0,1,Высшее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,8100.0,0,96.0,0.00
15215,0,35,1,0,1,Среднее специальное,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,9500.0,1,120.0,0.00
15216,0,61,1,0,0,Среднее,Не состоял в браке,Частная компания,Участие в основ. деятельности,13000.0,1,132.0,3300.00
15217,0,39,1,0,1,Среднее специальное,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,10000.0,0,108.0,0.00
15218,0,25,1,0,0,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,12000.0,0,48.0,0.00
15219,0,51,1,0,1,Среднее специальное,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,10000.0,0,156.0,0.00
15220,0,22,1,0,1,Среднее,Не состоял в браке,Индивидуальный предприниматель,Кадровая служба и секретариат,6000.0,0,48.0,0.00
15221,0,60,0,1,1,Среднее,Вдовец/Вдова,NaN,NaN,4500.0,0,NaN,0.00
15222,0,37,1,0,0,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,20000.0,0,36.0,0.00

Недостатком cut является необходимость задавать bin's в явном виде. От этого недостатка избавлен ее аналог - функция qcut.
Она использует эмпирические квантили, чтобы разделить данные. Если, например, мы хотим, чтобы данные разбились на  квартили - (0-25%), (25-50%], (50-70%], (75-100%) - мы можем просто указать 4 интервала

In [14]:
df = pd.read_csv('marketing_eng.csv')

In [ ]:
df2 = pd.DataFrame()

In [17]:
df2['newage'] = pd.qcut(df.AGE, 4

               newage
0        (39.0, 50.0]
1        (30.0, 39.0]
2        (50.0, 67.0]
3        (30.0, 39.0]
4      (20.999, 30.0]
5      (20.999, 30.0]
6        (30.0, 39.0]
7        (39.0, 50.0]
8        (50.0, 67.0]
9        (39.0, 50.0]
10       (50.0, 67.0]
11     (20.999, 30.0]
12       (50.0, 67.0]
13       (39.0, 50.0]
14       (30.0, 39.0]
15       (39.0, 50.0]
16       (50.0, 67.0]
17     (20.999, 30.0]
18       (30.0, 39.0]
19     (20.999, 30.0]
20       (30.0, 39.0]
21       (39.0, 50.0]
22       (39.0, 50.0]
23       (30.0, 39.0]
24       (30.0, 39.0]
25       (30.0, 39.0]
26     (20.999, 30.0]
27       (30.0, 39.0]
28       (39.0, 50.0]
29       (50.0, 67.0]
...               ...
15193    (30.0, 39.0]
15194    (39.0, 50.0]
15195    (50.0, 67.0]
15196    (50.0, 67.0]
15197    (50.0, 67.0]
15198    (39.0, 50.0]
15199  (20.999, 30.0]
15200    (30.0, 39.0]
15201    (50.0, 67.0]
15202    (30.0, 39.0]
15203    (39.0, 50.0]
15204    (39.0, 50.0]
15205    (30.0, 39.0]
15206    (50.0, 67.0]
15207  (20.999, 30.0]
15208    (30.0, 39.0]
15209    (39.0, 50.0]
15210  (20.999, 30.0]
15211    (30.0, 39.0]
15212    (50.0, 67.0]
15213    (30.0, 39.0]
15214    (30.0, 39.0]
15215    (30.0, 39.0]
15216    (50.0, 67.0]
15217    (30.0, 39.0]
15218  (20.999, 30.0]
15219    (50.0, 67.0]
15220  (20.999, 30.0]
15221    (50.0, 67.0]
15222    (30.0, 39.0]

[15223 rows x 1 columns]

In [21]:
df3 = pd.concat([df, df2], axis=1)

In [26]:
df4 = pd.get_dummies(df2)

In [27]:
df5 = pd.concat([df, df4], axis=1)

In [28]:
df5

,TARGET,AGE,SOCSTATUS_WORK_FL,SOCSTATUS_PENS_FL,GENDER,EDUCATION,MARITAL_STATUS,ORG_TP_STATE,JOB_DIR,PERSONAL_INCOME,OWN_AUTO,WORK_TIME,LOAN_MAX_DLQ_AMT,"newage_(20.999, 30.0]","newage_(30.0, 39.0]","newage_(39.0, 50.0]","newage_(50.0, 67.0]"
0,0,49,1,0,1,Среднее специальное,Состою в браке,Частная компания,Вспомогательный техперсонал,5000.0,0,18.0,1580.00,0,0,1,0
1,0,32,1,0,1,Среднее,Состою в браке,Индивидуальный предприниматель,Участие в основ. деятельности,12000.0,0,97.0,4020.00,0,1,0,0
2,0,52,1,0,1,Неполное среднее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,9000.0,0,84.0,0.00,0,0,0,1
3,0,39,1,0,1,Высшее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,25000.0,0,168.0,1590.00,0,1,0,0
4,0,30,1,0,0,Среднее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,12000.0,0,101.0,2230.00,1,0,0,0
5,0,29,1,0,0,Среднее,Гражданский брак,Частная компания,Адм-хоз. и трансп. службы,12000.0,1,40.0,0.00,1,0,0,0
6,0,35,1,0,0,Высшее,Разведен(а),Государственная комп./учреж.,Участие в основ. деятельности,15000.0,0,6.0,0.00,0,1,0,0
7,0,41,1,0,1,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,6000.0,0,6.0,0.00,0,0,1,0
8,0,53,1,0,0,Высшее,Состою в браке,Частная компания,Участие в основ. деятельности,100000.0,0,156.0,0.00,0,0,0,1
9,0,43,1,0,1,Среднее специальное,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,7000.0,0,72.0,0.00,0,0,1,0
10,0,54,1,0,1,Среднее специальное,Не состоял в браке,Государственная комп./учреж.,Пр-техн. обесп. и телеком.,19000.0,0,120.0,0.00,0,0,0,1
11,1,26,1,0,0,Среднее специальное,Не состоял в браке,Государственная комп./учреж.,Участие в основ. деятельности,18000.0,0,27.0,0.00,1,0,0,0
12,1,62,0,1,0,Среднее,Гражданский брак,Частная компания,Участие в основ. деятельности,7000.0,1,48.0,0.00,0,0,0,1
13,0,45,1,0,1,Среднее специальное,Разведен(а),Государственная комп./учреж.,Служба безопасности,12000.0,0,72.0,810.00,0,0,1,0
14,0,38,1,0,1,Высшее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,20000.0,0,120.0,0.00,0,1,0,0
15,1,41,1,0,1,Высшее,Разведен(а),Индивидуальный предприниматель,Участие в основ. деятельности,60000.0,0,168.0,0.00,0,0,1,0
16,0,65,0,1,1,Среднее специальное,Состою в браке,NaN,NaN,10000.0,0,NaN,0.00,0,0,0,1
17,0,29,1,0,1,Среднее специальное,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,5200.0,0,8.0,0.00,1,0,0,0
18,1,34,1,0,0,Среднее,Гражданский брак,Частная компания,Участие в основ. деятельности,35000.0,0,13.0,1439.94,0,1,0,0
19,0,28,1,0,1,Высшее,Не состоял в браке,Частная компания,Участие в основ. деятельности,15000.0,0,60.0,0.00,1,0,0,0
20,0,37,1,0,1,Высшее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,10000.0,0,192.0,0.00,0,1,0,0
21,0,42,1,0,1,Среднее специальное,Состою в браке,Частная компания,Участие в основ. деятельности,10000.0,0,76.0,0.00,0,0,1,0
22,0,45,1,0,1,Высшее,Разведен(а),Государственная комп./учреж.,Участие в основ. деятельности,14000.0,0,120.0,0.00,0,0,1,0
23,0,32,1,0,1,Среднее специальное,Не состоял в браке,Государственная комп./учреж.,Участие в основ. деятельности,10000.0,1,108.0,0.00,0,1,0,0
24,0,33,1,0,1,Среднее специальное,Состою в браке,Индивидуальный предприниматель,Участие в основ. деятельности,8000.0,0,24.0,0.00,0,1,0,0
25,0,38,1,0,1,Среднее специальное,Не состоял в браке,Индивидуальный предприниматель,Участие в основ. деятельности,13000.0,0,18.0,2742.25,0,1,0,0
26,0,27,1,0,1,Высшее,Состою в браке,Частная компания,Участие в основ. деятельности,12500.0,1,60.0,1411.31,1,0,0,0
27,1,31,1,0,1,Среднее специальное,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,12000.0,0,15.0,5760.00,0,1,0,0
28,0,40,1,0,0,Среднее специальное,Состою в браке,Частная компания,Участие в основ. деятельности,20000.0,0,2.0,0.00,0,0,1,0
29,0,63,0,1,1,Среднее специальное,Состою в браке,NaN,NaN,5000.0,0,NaN,0.00,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15193,0,36,1,0,1,Высшее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,12000.0,0,204.0,0.00,0,1,0,0
15194,0,49,1,0,1,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,10000.0,0,36.0,0.00,0,0,1,0
15195,0,51,1,1,1,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,10000.0,0,360.0,0.00,0,0,0,1
15196,0,64,0,1,1,Среднее,Вдовец/Вдова,NaN,NaN,8000.0,0,NaN,0.00,0,0,0,1
15197,0,61,0,1,1,Среднее специальное,Вдовец/Вдова,NaN,NaN,11000.0,0,NaN,0.00,0,0,0,1
15198,0,49,1,0,1,Среднее специальное,Состою в браке,Индивидуальный предприниматель,Участие в основ. деятельности,7000.0,0,72.0,0.00,0,0,1,0
15199,0,28,1,0,0,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,10000.0,0,18.0,0.00,1,0,0,0
15200,1,34,1,0,0,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,8000.0,0,36.0,605.59,0,1,0,0
15201,0,56,1,1,1,Высшее,Состою в браке,Частная компания,Участие в основ. деятельности,25000.0,0,84.0,0.00,0,0,0,1
15202,0,34,1,0,1,Среднее специальное,Состою в браке,Частная компания,Снабжение и сбыт,10000.0,0,7.0,0.00,0,1,0,0
15203,0,40,1,0,1,Среднее специальное,Состою в браке,Частная компания,Снабжение и сбыт,12000.0,0,8.0,0.00,0,0,1,0
15204,1,43,1,0,0,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,7000.0,0,27.0,0.00,0,0,1,0
15205,0,33,1,0,1,Высшее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,12000.0,0,160.0,0.00,0,1,0,0
15206,0,56,1,0,1,Среднее,Вдовец/Вдова,Частная компания,Участие в основ. деятельности,14500.0,0,384.0,0.00,0,0,0,1
15207,0,25,1,0,1,Среднее,Не состоял в браке,Индивидуальный предприниматель,Участие в основ. деятельности,12000.0,0,24.0,0.00,1,0,0,0
15208,0,37,1,0,1,Среднее специальное,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,8000.0,0,60.0,0.00,0,1,0,0
15209,1,48,1,0,1,Среднее специальное,Не состоял в браке,Частная компания,Участие в основ. деятельности,7000.0,0,6.0,0.00,0,0,1,0
15210,0,30,1,0,1,Среднее специальное,Состою в браке,Индивидуальный предприниматель,Участие в основ. деятельности,10000.0,0,12.0,0.00,1,0,0,0
15211,0,35,1,0,1,Высшее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,10000.0,0,48.0,0.00,0,1,0,0
15212,0,55,1,0,0,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,10000.0,1,204.0,0.00,0,0,0,1
15213,1,36,1,0,0,Среднее,Состою в браке,Частная компания,Вспомогательный техперсонал,15000.0,0,48.0,0.00,0,1,0,0
15214,0,31,1,0,1,Высшее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,8100.0,0,96.0,0.00,0,1,0,0
15215,0,35,1,0,1,Среднее специальное,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,9500.0,1,120.0,0.00,0,1,0,0
15216,0,61,1,0,0,Среднее,Не состоял в браке,Частная компания,Участие в основ. деятельности,13000.0,1,132.0,3300.00,0,0,0,1
15217,0,39,1,0,1,Среднее специальное,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,10000.0,0,108.0,0.00,0,1,0,0
15218,0,25,1,0,0,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,12000.0,0,48.0,0.00,1,0,0,0
15219,0,51,1,0,1,Среднее специальное,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,10000.0,0,156.0,0.00,0,0,0,1
15220,0,22,1,0,1,Среднее,Не состоял в браке,Индивидуальный предприниматель,Кадровая служба и секретариат,6000.0,0,48.0,0.00,1,0,0,0
15221,0,60,0,1,1,Среднее,Вдовец/Вдова,NaN,NaN,4500.0,0,NaN,0.00,0,0,0,1
15222,0,37,1,0,0,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,20000.0,0,36.0,0.00,0,1,0,0

### Выборка данных

Для выборки данных служит команда sample

In [131]:
df = pd.read_csv('marketing_eng.csv')

In [138]:
# n - сколько объектов вернуть в штуках

sample = df.sample(n=5)
sample

,TARGET,AGE,SOCSTATUS_WORK_FL,SOCSTATUS_PENS_FL,GENDER,EDUCATION,MARITAL_STATUS,ORG_TP_STATE,JOB_DIR,PERSONAL_INCOME,OWN_AUTO,WORK_TIME,LOAN_MAX_DLQ_AMT
8131,0,46,1,0,1,Среднее,Состою в браке,Государственная комп./учреж.,Вспомогательный техперсонал,5500.0,0,180.0,1420.0
14748,0,25,1,0,1,Высшее,Не состоял в браке,Частная компания,Участие в основ. деятельности,20000.0,0,16.0,0.0
673,0,39,1,0,1,Среднее специальное,Состою в браке,Индивидуальный предприниматель,Участие в основ. деятельности,18000.0,0,180.0,0.0
11991,0,49,1,0,1,Высшее,Состою в браке,Частная компания,Участие в основ. деятельности,16000.0,0,60.0,0.0
1628,0,35,1,0,1,Среднее специальное,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,7000.0,0,156.0,0.0

In [137]:
# frac - сколько объектов вернуть в % (0.1 = 10%)

sample = df.sample(frac=0.1)
sample

,TARGET,AGE,SOCSTATUS_WORK_FL,SOCSTATUS_PENS_FL,GENDER,EDUCATION,MARITAL_STATUS,ORG_TP_STATE,JOB_DIR,PERSONAL_INCOME,OWN_AUTO,WORK_TIME,LOAN_MAX_DLQ_AMT
6136,0,55,1,1,0,Среднее специальное,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,14000.0,1,96.0,0.0
4546,0,57,0,1,1,Среднее,Не состоял в браке,NaN,NaN,5400.0,0,NaN,0.0
8515,0,41,1,0,0,Среднее специальное,Разведен(а),Государственная комп./учреж.,Пр-техн. обесп. и телеком.,11000.0,0,204.0,0.0
12080,0,45,1,0,0,Высшее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,20000.0,0,7.0,0.0
559,0,35,1,0,0,Среднее специальное,Разведен(а),Некоммерческая организация,Участие в основ. деятельности,20000.0,0,41.0,0.0
3668,0,52,1,0,0,Среднее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,7000.0,0,76.0,0.0
3456,0,40,1,0,1,Среднее специальное,Состою в браке,Частная компания,Вспомогательный техперсонал,8000.0,1,18.0,0.0
13819,0,27,1,0,0,Высшее,Состою в браке,Частная компания,Бухгалтерия. финансы. планир.,40000.0,0,60.0,0.0
13002,0,26,1,0,1,Среднее специальное,Состою в браке,Частная компания,Участие в основ. деятельности,12000.0,0,48.0,0.0
4996,0,46,1,0,1,Среднее специальное,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,17000.0,0,324.0,0.0
7919,0,42,1,0,1,Среднее специальное,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,10000.0,0,252.0,0.0
1440,0,60,0,1,1,Среднее специальное,Состою в браке,NaN,NaN,5700.0,0,NaN,0.0
1699,0,22,1,0,0,Среднее специальное,Не состоял в браке,Частная компания,Участие в основ. деятельности,15000.0,0,48.0,0.0
1030,0,33,1,0,0,Высшее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,45000.0,1,45.0,0.0
13147,0,55,1,0,1,Среднее специальное,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,9000.0,0,48.0,0.0
11307,0,47,1,0,1,Высшее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,16000.0,0,206.0,0.0
4199,0,37,1,0,0,Высшее,Вдовец/Вдова,Частная компания,Участие в основ. деятельности,12000.0,0,18.0,0.0
3387,0,30,1,0,1,Среднее специальное,Состою в браке,Частная компания,Участие в основ. деятельности,12000.0,0,132.0,0.0
2487,0,39,1,0,1,Среднее специальное,Не состоял в браке,Частная компания,Участие в основ. деятельности,8000.0,0,12.0,0.0
3236,0,64,0,1,1,Среднее,Не состоял в браке,NaN,NaN,6500.0,0,NaN,776.3
127,0,38,1,0,0,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,38000.0,1,36.0,0.0
8583,0,57,1,0,0,Среднее,Разведен(а),Индивидуальный предприниматель,Участие в основ. деятельности,12000.0,0,6.0,0.0
3502,0,52,1,0,1,Среднее специальное,Не состоял в браке,Государственная комп./учреж.,Участие в основ. деятельности,7000.0,0,48.0,0.0
14577,0,27,1,0,0,Среднее,Не состоял в браке,Частная компания,Участие в основ. деятельности,12000.0,0,48.0,0.0
4455,1,31,1,0,1,Среднее специальное,Состою в браке,Частная компания,Участие в основ. деятельности,20000.0,1,18.0,0.0
276,0,59,1,0,0,Среднее специальное,Состою в браке,Некоммерческая организация,Участие в основ. деятельности,20000.0,0,36.0,0.0
1924,0,27,1,0,0,Среднее специальное,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,20000.0,0,36.0,0.0
13089,0,24,1,0,1,Высшее,Не состоял в браке,Частная компания,Участие в основ. деятельности,10000.0,0,6.0,0.0
13571,0,57,0,1,1,Среднее,Гражданский брак,NaN,NaN,5000.0,0,NaN,0.0
1027,0,54,1,0,0,Высшее,Не состоял в браке,Государственная комп./учреж.,Участие в основ. деятельности,8000.0,0,36.0,1150.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
11436,0,40,1,0,0,Среднее специальное,Состою в браке,Частная компания,Участие в основ. деятельности,23000.0,1,80.0,0.0
12906,0,45,1,0,1,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,15000.0,0,288.0,0.0
14277,1,53,1,0,1,Среднее,Разведен(а),Государственная комп./учреж.,Участие в основ. деятельности,15000.0,0,48.0,0.0
1881,0,43,1,0,1,Среднее специальное,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,8000.0,0,67.0,0.0
463,0,45,1,0,0,Среднее,Разведен(а),Государственная комп./учреж.,Участие в основ. деятельности,4500.0,0,36.0,0.0
10351,0,41,1,1,1,Среднее специальное,Вдовец/Вдова,Государственная комп./учреж.,Участие в основ. деятельности,20000.0,0,252.0,0.0
13327,0,41,1,0,1,Среднее,Состою в браке,Государственная комп./учреж.,Вспомогательный техперсонал,6000.0,0,108.0,0.0
465,0,51,1,0,1,Среднее специальное,Состою в браке,Индивидуальный предприниматель,Вспомогательный техперсонал,8000.0,0,7.0,2620.0
14620,0,51,1,0,0,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,9000.0,0,30.0,1010.0
11803,0,54,1,0,1,Среднее,Состою в браке,Государственная комп./учреж.,Вспомогательный техперсонал,10000.0,0,360.0,0.0
12169,1,52,1,0,1,Среднее,Состою в браке,Индивидуальный предприниматель,Участие в основ. деятельности,10000.0,0,48.0,0.0
10427,0,48,1,0,0,Среднее специальное,Не состоял в браке,Государственная комп./учреж.,Участие в основ. деятельности,12000.0,1,75.0,0.0
1270,0,52,1,0,0,Среднее специальное,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,12000.0,0,200.0,0.0
5204,0,44,1,0,0,Высшее,Состою в браке,Частная компания,Участие в основ. деятельности,10000.0,0,96.0,0.0
11796,0,50,1,0,1,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,12000.0,0,72.0,0.0
13332,0,58,0,1,1,Среднее,Состою в браке,NaN,NaN,2800.0,0,NaN,0.0
13853,1,28,1,0,1,Среднее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,15000.0,0,84.0,0.0
6462,0,31,1,0,0,Неполное среднее,Состою в браке,Государственная комп./учреж.,Вспомогательный техперсонал,12000.0,0,24.0,0.0
10699,0,32,1,0,0,Высшее,Состою в браке,Частная компания,Участие в основ. деятельности,30000.0,0,96.0,0.0
2915,0,25,1,0,0,Среднее специальное,Состою в браке,Частная компания,Участие в основ. деятельности,17000.0,1,36.0,0.0
13979,0,48,1,0,1,Среднее,Не состоял в браке,Государственная комп./учреж.,Участие в основ. деятельности,10000.0,0,264.0,367.0
4819,0,53,1,0,1,Среднее специальное,Не состоял в браке,Государственная комп./учреж.,Участие в основ. деятельности,20000.0,0,360.0,0.0
10854,0,40,1,0,0,Среднее специальное,Не состоял в браке,Частная компания,Участие в основ. деятельности,18000.0,0,72.0,0.0
12039,0,39,1,0,1,Среднее,Состою в браке,Государственная комп./учреж.,Участие в основ. деятельности,8000.0,0,48.0,0.0
6194,0,25,1,0,0,Высшее,Не состоял в браке,Государственная комп./учреж.,Участие в основ. деятельности,23000.0,0,5.0,0.0
6604,0,32,1,0,1,Среднее специальное,Не состоял в браке,Частная компания,Участие в основ. деятельности,19000.0,0,10.0,0.0
13042,0,63,0,1,1,Среднее специальное,Состою в браке,NaN,NaN,11000.0,0,NaN,0.0
767,0,56,1,1,1,Среднее специальное,Состою в браке,Государственная комп./учреж.,Вспомогательный техперсонал,8500.0,0,24.0,0.0
5423,0,26,1,0,0,Среднее,Состою в браке,Частная компания,Участие в основ. деятельности,25000.0,0,24.0,0.0
1342,0,28,1,0,1,Среднее специальное,Состою в браке,Частная компания,Участие в основ. деятельности,10000.0,0,12.0,0.0

In [139]:
original  = pd.Series([1,2,3,4,5])

In [144]:
original_sample = original.sample(n=10)
original_sample

ValueError: Cannot take a larger sample than population when 'replace=False'

In [145]:
original_sample = original.sample(n=10, replace=True)
original_sample

2    3
2    3
0    1
3    4
3    4
2    3
3    4
3    4
0    1
4    5
dtype: int64